### PR TITLE
fix: postgres -> "cannot truncate a table referenced in a foreign key constraint" error

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by emerleite** [comment]
Cool, @srghma. Can you please remove old Node.js versions from travis so tests will pass? 

I think this is the only thing we need to merge.

**Comment by srghma** [comment]
@emerleite done

**Comment by emerleite** [comment]
Just released 1.3.0 - https://www.npmjs.com/package/database-cleaner/v/1.3.0

Please upgrade it :)

**Comment by srghma** [comment]
thank you!

**Pull request merged**
