### PR TITLE
Allow passing a config file to the initialiazer

### PR DESCRIPTION
**Pull request by gabceb**
It would be nice to be able to override the cleaner-config. This is not a breaking change

### CODE REVIEW

**Comment by gabceb** [comment]
I have another PR waiting for this one with tests + https://github.com/emerleite/node-database-cleaner/issues/3 using async. Will create when this one gets merged

**Comment by gabceb** [comment]
Next PR is here https://github.com/gabceb/node-database-cleaner/commit/16bb9de62e3446169e94df9e6b2f89f09d11297e

**Comment by emerleite** [comment]
Hi @gabceb, thanks for de PR. I'll review and merge it this week.

**Comment by gabceb** [comment]
Thanks @emerleite

**Comment by emerleite** [comment]
@gabceb How about send the other PR? :)

**Pull request merged**
