### PR TITLE
Add elasticsearch support.

### PR DESCRIPTION
**Pull request by luizgpsantos**

### CODE REVIEW

**Comment by emerleite** [comment]
Hi @luizgpsantos, could you rebase it with passing tests, so I can merge it?

**Comment by emerleite** [comment]
Hi @luizgpsantos, just waiting for your PR update, so I can take a look and merge. I'm up to release a new version.

Cheers

**Comment by luizgpsantos** [comment]
Hi @emerleite it seems to be a problem when installing some dependencies in node 0.8 environment. In node 0.10 it worked well.

It's been a busy starting of the year, I will try to take a look as soon as possible.

**Comment by emerleite** [comment]
I guess I can remove 0.8 support.

Cheers

**Comment by emerleite** [comment]
@luizgpsantos merged. Thanks

**Pull request merged**
